library(dplyr)
mecha_mpg<- read.csv(file='/Users/adriennezane/Desktop/Data Bootcamp/MechaCar_Statistical_Analysis/MechaCar_mpg.csv')
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD + mpg, data=mecha_mpg)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD + mpg, data=mecha_mpg)) 
Coil_Data <- read.csv(file='/Users/adriennezane/Desktop/Data Bootcamp/MechaCar_Statistical_Analysis/Suspension_Coil.csv')
total_summary <- Coil_Data%>%summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI),.groups = 'keep') 
lot_summary <- Coil_Data%>% group_by(Manufacturing_Lot)%>%summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI),.groups = 'keep') 
